@baseUrl = http://localhost:3000
@contentType = application/json

### Create User
POST {{baseUrl}}/user
Content-Type: {{contentType}}

{
    "email": "john.doe@example.com",
    "name": "John Doe",
    "password": "password123"
}

### Get All Users
GET {{baseUrl}}/user
Content-Type: {{contentType}}

### Get User by ID
GET {{baseUrl}}/user/e0820ef8-a2ed-4d08-a6df-662d6803d576
Content-Type: {{contentType}}

### Update User
PATCH {{baseUrl}}/user/e0820ef8-a2ed-4d08-a6df-662d6803d576
Content-Type: {{contentType}}

{
    "name": "John Doe Updated",
    "email": "john.updated@example.com"
}

### Delete User
DELETE {{baseUrl}}/user/e0820ef8-a2ed-4d08-a6df-662d6803d576
Content-Type: {{contentType}}
