@baseUrl = http://localhost:3000
@contentType = application/json

### Create User
POST {{baseUrl}}/user
Content-Type: {{contentType}}

{
    "email": "john.doe@example.com",
    "name": "John Doe",
    "password": "password123"
}

### Get All Users
GET {{baseUrl}}/user
Content-Type: {{contentType}}

### Get User by ID
GET {{baseUrl}}/user/3fee99a1-58de-4fd8-b104-607a5a08630e
Content-Type: {{contentType}}

### Update User
PATCH {{baseUrl}}/user/3fee99a1-58de-4fd8-b104-607a5a08630e
Content-Type: {{contentType}}

{
    "name": "John Doe Updated",
    "email": "john.updated@example.com"
}

### Delete User
DELETE {{baseUrl}}/user/3fee99a1-58de-4fd8-b104-607a5a08630e
Content-Type: {{contentType}}
